name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta diariamente
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: pankyiiii
          svg_output_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
